SPG_Fachtheorie/SPG_Fachtheorie.Aufgabe3RazorPages/Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SPG_Fachtheorie.Aufgabe3RazorPages.Pages;

[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
[IgnoreAntiforgeryToken]
public class ErrorModel : PageModel
{
    public string RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

    private readonly ILogger<ErrorModel> _logger;

    public ErrorModel(ILogger<ErrorModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
        RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
    }
}

SPG_Fachtheorie/SPG_Fachtheorie.Aufgabe3RazorPages/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using SPG_Fachtheorie.Aufgabe2;
using SPG_Fachtheorie.Aufgabe2.Model;
using SPG_Fachtheorie.Aufgabe3RazorPages.Services;

namespace SPG_Fachtheorie.Aufgabe3RazorPages.Pages
{
    public class IndexModel : PageModel
    {
        private readonly AppointmentContext _db;
        private readonly AuthService _authService;
        public IndexModel(AppointmentContext db, AuthService authService)
        {
            _db = db;
            _authService = authService;
        }

        public string CurrentUser => _authService.Username;
        public List<Student> Students { get; set; } = new();
        public List<SelectListItem> UserItems { get; set; } = new();
        [BindProperty]
        public string SelectedUser { get; set; }
        public void OnGet()
        {
            Students = _db.Students.ToList();
            UserItems = Students.Select(s => new SelectListItem
            {
                Text = $"{s.Username} - {s.Lastname} {s.Firstname} (Coach: {(s is Coach ? "Ja" : "Nein")})",
                Value = s.Username
            })
            .ToList();
        }

        public async Task<IActionResult> OnPostLogout()
        {
            await _authService.Logout();
            return RedirectToPage();
        }

        public async Task<IActionResult> OnPost()
        {
            await _authService.TryLogin(SelectedUser);
            return RedirectToPage();
        }
    }
}

SPG_Fachtheorie/SPG_Fachtheorie.Aufgabe3RazorPages/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SPG_Fachtheorie.Aufgabe3RazorPages.Pages;

public class PrivacyModel : PageModel
{
    private readonly ILogger<PrivacyModel> _logger;

    public PrivacyModel(ILogger<PrivacyModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
    }
}

SPG_Fachtheorie/SPG_Fachtheorie.Aufgabe3RazorPages/Pages/Index.cshtml
@page
@using SPG_Fachtheorie.Aufgabe2.Model
@model IndexModel

<div>
    <h1 class="h3">Klausurprüfung aus Fachtheorie</h1>
    <p>Bitte füllen Sie diese Daten in der Datei <em>SPG_Fachtheorie.Aufgabe3RazorPages/Pages/Index.cshtml</em> am Beginn Ihrer Arbeit aus.</p>
    <table class="table table-sm mb-5 border border-primary">
        <tr>
            <th style="width:10em">Maturaaccount</th>
            <td style="width:30em">(Bitte ausfüllen)</td>
        </tr>
        <tr>
            <th>Vorname</th>
            <td>(Bitte ausfüllen)</td>
        </tr>
        <tr>
            <th>Zuname</th>
            <td>(Bitte ausfüllen)</td>
        </tr>
        <tr>
            <th>Klasse</th>
            <td>(Bitte ausfüllen)</td>
        </tr>
    </table>
</div>
<div class="mb-3">
    @if (Model.CurrentUser is not null)
    {
        <h5>Angemeldet als User @Model.CurrentUser</h5>
        <form method="post" asp-page-handler="logout">
            <button class="btn btn-primary">Logout</button>
        </form>

    }
    else
    {
        <h5>
            Wähle einen User aus:
        </h5>
        <form method="post">
            <select asp-for="SelectedUser"
                class="form-control"
                asp-items="Model.UserItems"></select>
            <button class="btn btn-primary">Login</button>
        </form>
    }
</div>
<div>
    <h1 class="h5">Daten der Tabelle Student</h1>
    <p>Diese Tabelle dient zum Testen des Datenbankzugriffes.</p>
</div>
<table class="table table-sm">
    <thead>
        <tr>
            <th>GUID</th>
            <th>Username</th>
            <th>Name</th>
            <th>Rolle</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var s in Model.Students)
        {
            <tr>
                <td>@s.Id</td>
                <td>@s.Username</td>
                <td>@s.Lastname @s.Firstname</td>
                <td>@(s is Coach ? "Coach" : "Student")</td>
            </tr>
        }
    </tbody>
</table>

SPG_Fachtheorie/SPG_Fachtheorie.Aufgabe3RazorPages/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SPG_Fachtheorie.Aufgabe3RazorPages</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SPG_Fachtheorie.Aufgabe3RazorPages.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">SPG_Fachtheorie.Aufgabe3RazorPages</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - SPG_Fachtheorie.Aufgabe3RazorPages - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>